# https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "buildah-rs"
version = "0.1.0"
authors = ["Dennis Krasnov <dennis@krasnov.dev>"]
edition = "2018"

[dependencies]
tracing = "0.1"
