name: Continuous Integration and Deployment

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
        
    - name: Build Rust binary
      run: cargo build --verbose
      
    - name: Run Rust tests
      run: cargo test --verbose
      
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to crates.io
        run: cargo login ${{ secrets.CRATES_IO_ACCESS_TOKEN }}

      - name: Publish to crates.io
        run: cargo publish
